Add agent user having minimum privileges to the dockerfile
newrelic/infrastructure-bundle pull request #144
Opened 2021-12-14 14:25 UTC by alvarocabanas

- We add the user that is used only in K8s unprivileged mode. This user has no privileges so it's secure to add it in any environment.

2021-12-15 09:56 UTC, roobre requested changes

2021-12-15 09:56 UTC, roobre commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
Do we need this to run the image in an unprivileged scenario?
I think I be able to just set the `securityContext` to whatever UID I want, whether it exists in the docker image or not. This will give cluster admins more flexibility on which IDs to use.

2021-12-15 09:57 UTC, roobre commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
I am aware of this being in the unprivileged image before, but I never fully understood why 🤔

2021-12-15 09:58 UTC, roobre commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
Something we should ensure though, is that all integration binaries are `chmod`ed appropriately so any user can run them.

2021-12-15 10:05 UTC, alvarocabanas commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
Good point, I can check it further.

2021-12-15 11:35 UTC, paologallinaharbur commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
basically the idea was to avoid reporting the process sample having just the ID. Also when checking processes (es ps) if the user is not present the id only is shown. Now a big deal cosmetical thing that in some really weird scenario could  represent a very small breaking change

2021-12-15 13:31 UTC, roobre commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
But in unprivileged mode we won't be reporting processes, right? And in privileged mode the user will be `root`.

2021-12-15 13:46 UTC, paologallinaharbur commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
I believe they do, but some metrics are missing https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/linux-agent-running-modes/#mode-metrics

2021-12-28 08:19 UTC, rubenruizdegauna commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
I see that this is already present in the infra-agent Dockerfile https://github.com/newrelic/infrastructure-agent/blob/master/build/container/Dockerfile#L55 

WDYT if we move that to the base image so it gets propagated? any downside?

2021-12-28 08:55 UTC, roobre commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
@rubenruizdegauna I cannot think about any downside from our side, but for now we're still working on deciding if this is something we require or not :)
We'll ping you when we decide if we are going to need this or not (might require some testing)

2022-01-26 08:52 UTC, alvarocabanas commented on Dockerfile
> +RUN addgroup -g 2000 nri-agent && adduser -D -u 1000 -G nri-agent nri-agent
We have realized this is not needed so we will close this PR

2022-01-26 08:53 UTC, alvarocabanas commented
We thought we needed these user creation for the new nri-kubernetes, but we have been using this image without having that user created and we have not spotted any issue.

2022-01-26 08:53 UTC, closed without merging